### Click here to toggle on/off the raw code

In [110]:
from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

### hide_toggle

In [116]:
from IPython.display import HTML
import random

def hide_toggle(for_next=False):
    this_cell = """$('div.cell.code_cell.rendered.selected')"""
    next_cell = this_cell + '.next()'

    toggle_text = 'Toggle show/hide'  # text shown on toggle link
    target_cell = this_cell  # target cell to control with toggle
    js_hide_current = ''  # bit of JS to permanently hide code in current cell (only when toggling next cell)

    if for_next:
        target_cell = next_cell
        toggle_text += ' next cell'
        js_hide_current = this_cell + '.find("div.input").hide();'

    js_f_name = 'code_toggle_{}'.format(str(random.randint(1,2**64)))

    html = """
        <script>
            function {f_name}() {{
                {cell_selector}.find('div.input').toggle();
            }}

            {js_hide_current}
        </script>

        <a href="javascript:{f_name}()">{toggle_text}</a>
    """.format(
        f_name=js_f_name,
        cell_selector=target_cell,
        js_hide_current=js_hide_current, 
        toggle_text=toggle_text
    )

    return HTML(html)

hide_toggle()

### Importing required packages

In [118]:
import pandas as pd
import numpy as np
from IPython.display import display,HTML
import subprocess
import sys

# !pip install jupyter_contrib_nbextensions
# !pip3 install jupyter_contrib_nbextensions
# !jupyter contrib nbextension install --user
# !pip install jupyter_nbextensions_configurator
# !pip3 install jupyter_nbextensions_configurator
# !jupyter nbextensions_configurator enable --user

#!jupyter nbextension enable codefolding/main
# To disable: !jupyter nbextension disable codefolding/main

# http://localhost:8888/nbextensions/

Enabling notebook extension codefolding/main...
      - Validating: OK


### Installing required packages

In [114]:
import subprocess
import sys
from IPython.display import display,HTML

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])   
install("jupyter_contrib_nbextensions")
install("ipynb")   # for importing functions from other .ipynb files

You should consider upgrading via the 'pip install --upgrade pip' command.


You should consider upgrading via the 'pip install --upgrade pip' command.


### Embedding Python child processes in Pandas array

In [117]:
import numpy as np
import pandas as pd
display(
    (pd.array([
            np.abs([-2,-2,-----+-2]),
            np.array([2,3,4]),
            np.absolute([-2,-2,-----+-2]),
            np.add([2,3],[2,3]),
            #np.alen([[1,2,3],[3,2]]),  # 2
            np.all([1,-2,0]), #Test whether all array elements along a given axis evaluate to True.
            np.any([0,0,0]),
            np.alltrue([1,1,-1]),
            np.zeros([5]),
            np.zeros(10)+5,
            np.zeros([2,3,4]),
            np.zeros([2,2,3,4]),
            np.zeros([2,2,2,3,4]),
            display(
                np.ones(5),
                np.linspace(0,2,5,210000000),  # 21 elements in range of [0,21]
                np.random.rand(2,2,3,3000),
                np.random.rand(5,2),
                np.random.randint(0,22,(2,4,2)),
                np.random.seed(42), #Hitchhiker's Guide to the Galaxy
                np.random.rand(4)
            ),
            subprocess.run(["python3","-c",'''
print("Inside matplotlib subprocess")
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2*np.pi*t)
plt.plot(t, s)

plt.xlabel('time (s)')
plt.ylabel('voltage (mV)')
plt.title('About as simple as it gets, folks')
plt.grid(True)
plt.savefig("test.png")
plt.show()
            ''']).stdout
            ,subprocess.run(["python3","-c",'''
print("Inside subprocess")
import subprocess
import sys
from pprint import pprint as pr
from IPython.display import display,HTML

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])   
install("numpy")
install("pandas")


import numpy as np
arr = np.arange(0,11)
arr_ = arr[:]
arr_[-1] = 1000
arr_copy = arr.copy()[:]
arr_copy[-1] = 100
display(
    pr(arr),
    pr(arr[0:5]),
    pr(arr[0:-5]),
    pr(arr[-5:0]),
    pr(arr[:]),
    pr(arr_[:]),  # changes the original array
    pr(arr_copy[:]),  # does not change the original array
    pr(ar>4),   # will show error
    pr(arr[arr>4]),
)
''']).stdout,
            subprocess.run(["python3","-c",'''
# Run this program on your local python
# interpreter, provided you have installed
# the required libraries.
import subprocess,sys
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])   
install("numpy")
install("sklearn")

# Importing the required packages
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Function importing Dataset
def importdata():
	balance_data = pd.read_csv(
'https://archive.ics.uci.edu/ml/machine-learning-'+
'databases/balance-scale/balance-scale.data',
	sep= ',', header = None)
	
	# Printing the dataswet shape
	print ("Dataset Length: ", len(balance_data))
	print ("Dataset Shape: ", balance_data.shape)
	
	# Printing the dataset obseravtions
	print ("Dataset: ",balance_data.head())
	return balance_data

# Function to split the dataset
def splitdataset(balance_data):

	# Separating the target variable
	X = balance_data.values[:, 1:5]
	Y = balance_data.values[:, 0]

	# Splitting the dataset into train and test
	X_train, X_test, y_train, y_test = train_test_split(
	X, Y, test_size = 0.3, random_state = 100)
	
	return X, Y, X_train, X_test, y_train, y_test
	
# Function to perform training with giniIndex.
def train_using_gini(X_train, X_test, y_train):

	# Creating the classifier object
	clf_gini = DecisionTreeClassifier(criterion = "gini",
			random_state = 100,max_depth=3, min_samples_leaf=5)

	# Performing training
	clf_gini.fit(X_train, y_train)
	return clf_gini
	
# Function to perform training with entropy.
def tarin_using_entropy(X_train, X_test, y_train):

	# Decision tree with entropy
	clf_entropy = DecisionTreeClassifier(
			criterion = "entropy", random_state = 100,
			max_depth = 3, min_samples_leaf = 5)

	# Performing training
	clf_entropy.fit(X_train, y_train)
	return clf_entropy


# Function to make predictions
def prediction(X_test, clf_object):

	# Predicton on test with giniIndex
	y_pred = clf_object.predict(X_test)
	print("Predicted values:")
	print(y_pred)
	return y_pred
	
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
	
	print("Confusion Matrix: ",
		confusion_matrix(y_test, y_pred))
	
	print ("Accuracy : ",
	accuracy_score(y_test,y_pred)*100)
	
	print("Report : ",
	classification_report(y_test, y_pred))

# Driver code
def main():
	
	# Building Phase
	data = importdata()
	X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
	clf_gini = train_using_gini(X_train, X_test, y_train)
	clf_entropy = tarin_using_entropy(X_train, X_test, y_train)
	
	# Operational Phase
	print("Results Using Gini Index:")
	
	# Prediction using gini
	y_pred_gini = prediction(X_test, clf_gini)
	cal_accuracy(y_test, y_pred_gini)
	
	print("Results Using Entropy:")
	# Prediction using entropy
	y_pred_entropy = prediction(X_test, clf_entropy)
	cal_accuracy(y_test, y_pred_entropy)
	
	
# Calling main function
if __name__=="__main__":
	main()

''']).stdout,
    ]))
)

hide_toggle()

array([1., 1., 1., 1., 1.])

array([0. , 0.5, 1. , 1.5, 2. ])

array([[[[0.15601864, 0.15599452, 0.05808361, ..., 0.7966814 ,
          0.2504679 , 0.6248741 ],
         [0.57174598, 0.83283038, 0.90608706, ..., 0.17238636,
          0.87239456, 0.61311624],
         [0.15720388, 0.96233806, 0.51836546, ..., 0.52536048,
          0.72491027, 0.4360483 ]],

        [[0.63003458, 0.34057594, 0.30115902, ..., 0.08003257,
          0.24232981, 0.77367935],
         [0.52868585, 0.92796906, 0.42875141, ..., 0.74674677,
          0.56266678, 0.08330258],
         [0.18558024, 0.21932818, 0.25786425, ..., 0.40241849,
          0.47190911, 0.71672478]]],


       [[[0.87630603, 0.2722188 , 0.3420768 , ..., 0.48114436,
          0.78895834, 0.07350828],
         [0.19159397, 0.55153425, 0.94708832, ..., 0.46757096,
          0.0557069 , 0.91851015],
         [0.98032913, 0.43104342, 0.61366081, ..., 0.02628985,
          0.91099702, 0.30574519]],

        [[0.5082227 , 0.13229552, 0.90225497, ..., 0.45929245,
          0.96449852, 0.21897845],
         [0.

array([[0.83737803, 0.53644521],
       [0.80750873, 0.85332328],
       [0.44262622, 0.35898294],
       [0.45543327, 0.6527952 ],
       [0.36715915, 0.77498829]])

array([[[10, 15],
        [17, 14],
        [ 5,  7],
        [ 3, 20]],

       [[15, 20],
        [10, 19],
        [ 1, 21],
        [ 3, 13]]])

None

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

Inside matplotlib subprocess
Figure(640x480)


You should consider upgrading via the 'pip install --upgrade pip' command.


You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 28, in <module>
NameError: name 'ar' is not defined


Inside subprocess
array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9, 1000])
array([0, 1, 2, 3, 4])
array([0, 1, 2, 3, 4, 5])
array([], dtype=int64)
array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9, 1000])
array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9, 1000])
array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100])


You should consider upgrading via the 'pip install --upgrade pip' command.


You should consider upgrading via the 'pip install --upgrade pip' command.


Dataset Length:  625
Dataset Shape:  (625, 5)
Dataset:     0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5
Results Using Gini Index:
Predicted values:
['R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'L'
 'L' 'R' 'L' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L'
 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'R'
 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'L' 'L' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'R' 'R' 'L' 'R' 'L'
 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L'
 'L' 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R'
 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R'
 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'R' 'R'
 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'R']
Confusion Matrix:  [[ 0  6  7]
 [ 

/Users/sreedhar.k/.pyenv/versions/3.8.0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sreedhar.k/.pyenv/versions/3.8.0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sreedhar.k/.pyenv/versions/3.8.0/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_

<PandasArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         array([2, 2, 2]),
                                                                                                                                                                                                                                                                                              

### Intro to pandas

In [7]:
ages = {
    "sam":5,
    "tram":3,
    "ram":4
}
ages_ = {
    "sam":5,
    "tram_":3,
    "ram_":4
}
display(
    pd.Series(ages),
    #pd.DataFrame(data=ages)
    ages["sam"],
    ages.keys(),
    list(ages.keys()),
    ages.copy(),
    ages.values(),
    np.array([5,2])*2,
    pd.Series([5,2])*2,
    pd.Series(ages) + pd.Series(ages_),
    pd.Series(ages).add(pd.Series(ages_),fill_value=0),
    pd.Series(ages).dtype,
    pd.Series(ages).add(pd.Series(ages_),fill_value=0).dtype,
)

np.random.seed(101)
myindex = ['CA','LA','AZ','TX']
mycolumns = ['JAN','FEB','MAR']
mydata = np.random.randint(0,101,(4,3))
df = pd.DataFrame(data=mydata,index=myindex,columns = mycolumns)



display(
    mydata,
    df,
    df.info(),
)


sam     5
tram    3
ram     4
dtype: int64

5

dict_keys(['sam', 'tram', 'ram'])

['sam', 'tram', 'ram']

{'sam': 5, 'tram': 3, 'ram': 4}

dict_values([5, 3, 4])

array([10,  4])

0    10
1     4
dtype: int64

ram       NaN
ram_      NaN
sam      10.0
tram      NaN
tram_     NaN
dtype: float64

ram       4.0
ram_      4.0
sam      10.0
tram      3.0
tram_     3.0
dtype: float64

dtype('int64')

dtype('float64')

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   JAN     4 non-null      int64
 1   FEB     4 non-null      int64
 2   MAR     4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes


array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

JAN  FEB  MAR
CA   95   11   81
LA   70   63   87
AZ   75    9   77
TX   40    4   63

None

### Working with csv and xlsx files

In [8]:
df = pd.read_csv('datasets/tips.csv')
df["price_per_person"] = round(df['total_bill']/df['size'],2)
df['tip_percentage'] = 100 * df['tip']/df['total_bill']
df['Payment_ID'] = str(100 * df['tip']/df['total_bill'])
for i in range(df.shape[0]):
    df['Payment_ID'][i]  = "Sun_" + str(i)


display(
    df,
    df.columns,
    df.index,
    df.info(),
    df.describe().columns,
    df.describe().index, #Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='object')
    
)



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   tip_percentage    244 non-null    float64
 9   Payment_ID        244 non-null    object 
dtypes: float64(4), int64(1), object(5)
memory usage: 19.2+ KB


/var/folders/vh/30ml2jmd6t76y5lwy1jflql5f0c2kc/T/ipykernel_73335/1646646716.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Payment_ID'][i]  = "Sun_" + str(i)


total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

     tip_percentage Payment_ID  
0          5.944673      Sun_0  
1         16.054159      Sun_1  
2         16.658734      Sun_2  
3         13.978041      Sun_3  
4         14.680765      Sun_4  
..              ...        ...  
239       20.392697    Sun_239  
240        7.358352    Sun_240  
241        8.822232    Sun_241  
242        9.820426    Sun_242  
243       15.974441    Sun_243  

[244 rows x 10 columns]

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'tip_percentage', 'Payment_ID'],
      dtype='object')

RangeIndex(start=0, stop=244, step=1)

None

Index(['total_bill', 'tip', 'size', 'price_per_person', 'tip_percentage'], dtype='object')

Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='object')

In [9]:

display(
    df.head(),
    df.tail(),
    df.ndim,
    df.shape,
    df.index[0],
)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

   tip_percentage Payment_ID  
0        5.944673      Sun_0  
1       16.054159      Sun_1  
2       16.658734      Sun_2  
3       13.978041      Sun_3  
4       14.680765      Sun_4

total_bill   tip     sex smoker   day    time  size  price_per_person  \
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

     tip_percentage Payment_ID  
239       20.392697    Sun_239  
240        7.358352    Sun_240  
241        8.822232    Sun_241  
242        9.820426    Sun_242  
243       15.974441    Sun_243

2

(244, 10)

0

In [13]:
#df.set_index('Payment_ID',inplace=True)
display(
    df,
    df.iloc[0:5],
    df.loc[['Sun_0','Sun_2']],  
)

total_bill   tip     sex smoker   day    time  size  \
Payment_ID                                                        
Sun_0            16.99  1.01  Female     No   Sun  Dinner     2   
Sun_1            10.34  1.66    Male     No   Sun  Dinner     3   
Sun_2            21.01  3.50    Male     No   Sun  Dinner     3   
Sun_3            23.68  3.31    Male     No   Sun  Dinner     2   
Sun_4            24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sun_239          29.03  5.92    Male     No   Sat  Dinner     3   
Sun_240          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sun_241          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sun_242          17.82  1.75    Male     No   Sat  Dinner     2   
Sun_243          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person  tip_percentage  
Payment_ID                                    
Sun_0                   8.49        5.944673  
Sun_1                   3.45       16.054159  
Sun_2                   7.00       16.658734  
Sun_3                  11.84       13.978041  
Sun_4                   6.15       14.680765  
...                      ...             ...  
Sun_239                 9.68       20.392697  
Sun_240                13.59        7.358352  
Sun_241                11.34        8.822232  
Sun_242                 8.91        9.820426  
Sun_243                 9.39       15.974441  

[244 rows x 9 columns]

total_bill   tip     sex smoker  day    time  size  \
Payment_ID                                                       
Sun_0            16.99  1.01  Female     No  Sun  Dinner     2   
Sun_1            10.34  1.66    Male     No  Sun  Dinner     3   
Sun_2            21.01  3.50    Male     No  Sun  Dinner     3   
Sun_3            23.68  3.31    Male     No  Sun  Dinner     2   
Sun_4            24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person  tip_percentage  
Payment_ID                                    
Sun_0                   8.49        5.944673  
Sun_1                   3.45       16.054159  
Sun_2                   7.00       16.658734  
Sun_3                  11.84       13.978041  
Sun_4                   6.15       14.680765

total_bill   tip     sex smoker  day    time  size  \
Payment_ID                                                       
Sun_0            16.99  1.01  Female     No  Sun  Dinner     2   
Sun_2            21.01  3.50    Male     No  Sun  Dinner     3   

            price_per_person  tip_percentage  
Payment_ID                                    
Sun_0                   8.49        5.944673  
Sun_2                   7.00       16.658734

### Generate credit card numbers

In [35]:
from random import choices
from string import digits

df['CC_Number'] = str(100 * df['tip']/df['total_bill'])
for i in range(df.shape[0]):
    df['CC_Number'][i]  = str("".join(choices(digits, k=16)))
    
display(df)

/var/folders/vh/30ml2jmd6t76y5lwy1jflql5f0c2kc/T/ipykernel_73335/725399878.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CC_Number'][i]  = str("".join(choices(digits, k=16)))


total_bill   tip     sex smoker   day    time  size  \
Payment_ID                                                        
Sun_0            16.99  1.01  Female     No   Sun  Dinner     2   
Sun_1            10.34  1.66    Male     No   Sun  Dinner     3   
Sun_2            21.01  3.50    Male     No   Sun  Dinner     3   
Sun_3            23.68  3.31    Male     No   Sun  Dinner     2   
Sun_4            24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sun_239          29.03  5.92    Male     No   Sat  Dinner     3   
Sun_240          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sun_241          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sun_242          17.82  1.75    Male     No   Sat  Dinner     2   
Sun_243          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person  tip_percentage         CC_Number  
Payment_ID                                                      
Sun_0                   8.49        5.944673  9815674310016831  
Sun_1                   3.45       16.054159  3109632351007638  
Sun_2                   7.00       16.658734  0705077532117862  
Sun_3                  11.84       13.978041  8583976977556589  
Sun_4                   6.15       14.680765  6484759993175081  
...                      ...             ...               ...  
Sun_239                 9.68       20.392697  7529136818987142  
Sun_240                13.59        7.358352  4658126455325515  
Sun_241                11.34        8.822232  0516091093982043  
Sun_242                 8.91        9.820426  7976585358665221  
Sun_243                 9.39       15.974441  8258261145264902  

[244 rows x 10 columns]

### Dropping by row number , concatenating dataframes, conditional filtering

#### 1. Lambda functions

In [65]:
# df.drop('Sun_0')

n = 3
def multiple_columns():
    display(
        pd.concat([df.iloc[:n-1],df.iloc[n:]]),  # by row number
        df[df.index!='Sun_0'],   # by index
        df[df["total_bill"]>15],  # by any column other than index
        df[(df["total_bill"]>15) & (df["sex"]=="Male") ],
        df[(df["total_bill"]>15) | (df["sex"]=="Male") ],
        df[(df["day"].isin(["Fri","Sat","Sun"]))],
    )
#multiple_columns()

df['CC_last_four'] = df['CC_Number'].apply(lambda a : a[-4:])
df['yelp'] = df['total_bill'].apply(
                                      lambda price:
                                          ("$") if((price)<10)
                                          else ("$$") if(price>=10 and price<30)
                                          else ("$$$")
                                  )
def apply_methods():
    display(
        df,
    )
    
#apply_methods()


df["Quality"] = df[['total_bill','tip']].apply(
                              lambda df:
                                  "Generous" if((df['tip']/df['total_bill'])>0.25)
                                  else "Other",
                              axis=1
                          )

def multiple_applies():
    display(
        df[df["Quality"]=="Generous"],
        df,
    )
    
    
#multiple_applies()


total_bill   tip     sex smoker   day    time  size  \
Payment_ID                                                        
Sun_51           10.29  2.60  Female     No   Sun  Dinner     2   
Sun_67            3.07  1.00  Female    Yes   Sat  Dinner     1   
Sun_93           16.32  4.30  Female    Yes   Fri  Dinner     2   
Sun_109          14.31  4.00  Female    Yes   Sat  Dinner     2   
Sun_149           7.51  2.00    Male     No  Thur   Lunch     2   
Sun_172           7.25  5.15    Male    Yes   Sun  Dinner     2   
Sun_178           9.60  4.00  Female    Yes   Sun  Dinner     2   
Sun_183          23.17  6.50    Male    Yes   Sun  Dinner     4   
Sun_221          13.42  3.48  Female    Yes   Fri   Lunch     2   
Sun_232          11.61  3.39    Male     No   Sat  Dinner     2   

            price_per_person  tip_percentage         CC_Number CC_last_four  \
Payment_ID                                                                    
Sun_51                  5.14       25.267250  2664432672194994         4994   
Sun_67                  3.07       32.573290  7347587509976138         6138   
Sun_93                  8.16       26.348039  7931802678161309         1309   
Sun_109                 7.16       27.952481  9330635659749447         9447   
Sun_149                 3.76       26.631158  9685634291487336         7336   
Sun_172                 3.62       71.034483  7986179117242763         2763   
Sun_178                 4.80       41.666667  1069017067272654         2654   
Sun_183                 5.79       28.053517  0549941735565396         5396   
Sun_221                 6.71       25.931446  7978471365528086         8086   
Sun_232                 5.80       29.198966  9907638924678069         8069   

           yelp   Quality  
Payment_ID                 
Sun_51       $$  Generous  
Sun_67        $  Generous  
Sun_93       $$  Generous  
Sun_109      $$  Generous  
Sun_149       $  Generous  
Sun_172       $  Generous  
Sun_178       $  Generous  
Sun_183      $$  Generous  
Sun_221      $$  Generous  
Sun_232      $$  Generous

total_bill   tip     sex smoker   day    time  size  \
Payment_ID                                                        
Sun_0            16.99  1.01  Female     No   Sun  Dinner     2   
Sun_1            10.34  1.66    Male     No   Sun  Dinner     3   
Sun_2            21.01  3.50    Male     No   Sun  Dinner     3   
Sun_3            23.68  3.31    Male     No   Sun  Dinner     2   
Sun_4            24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sun_239          29.03  5.92    Male     No   Sat  Dinner     3   
Sun_240          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sun_241          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sun_242          17.82  1.75    Male     No   Sat  Dinner     2   
Sun_243          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person  tip_percentage         CC_Number CC_last_four  \
Payment_ID                                                                    
Sun_0                   8.49        5.944673  9815674310016831         6831   
Sun_1                   3.45       16.054159  3109632351007638         7638   
Sun_2                   7.00       16.658734  0705077532117862         7862   
Sun_3                  11.84       13.978041  8583976977556589         6589   
Sun_4                   6.15       14.680765  6484759993175081         5081   
...                      ...             ...               ...          ...   
Sun_239                 9.68       20.392697  7529136818987142         7142   
Sun_240                13.59        7.358352  4658126455325515         5515   
Sun_241                11.34        8.822232  0516091093982043         2043   
Sun_242                 8.91        9.820426  7976585358665221         5221   
Sun_243                 9.39       15.974441  8258261145264902         4902   

           yelp Quality  
Payment_ID               
Sun_0        $$   Other  
Sun_1        $$   Other  
Sun_2        $$   Other  
Sun_3        $$   Other  
Sun_4        $$   Other  
...         ...     ...  
Sun_239      $$   Other  
Sun_240      $$   Other  
Sun_241      $$   Other  
Sun_242      $$   Other  
Sun_243      $$   Other  

[244 rows x 13 columns]

### Describing and Sorting

1. max() simply returns the maximum value.
2. idmax() returns the index of the (first occurrence of the) maximum value, not the maximum value itself.

In [105]:
df = pd.read_csv("datasets/tips.csv")
display(
    df.describe(),
    df.describe().transpose(),
    df.iloc[df["total_bill"].idxmax()],
    df.sort_values("total_bill").iloc[len(df)-1],
    len(df[df["sex"]=="Female"]),
    len(df[df["sex"]=="Male"]),
    df['sex'].value_counts(),
    df['smoker'].value_counts(),
    df['sex'].replace(["Female","Male"],["F","M"],inplace=True),
    df['sex'].map({"F":"Female","M":"Male"}),
    df['sex'].replace(["Female","Male"],["F","M"],inplace=True),
    df,
)

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

total_bill     50.81
tip             10.0
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               3
Name: 170, dtype: object

total_bill     50.81
tip             10.0
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               3
Name: 170, dtype: object

87

157

Male      157
Female     87
Name: sex, dtype: int64

No     151
Yes     93
Name: smoker, dtype: int64

None

0      Female
1        Male
2        Male
3        Male
4      Female
        ...  
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: object

None

total_bill   tip sex smoker   day    time  size
0         16.99  1.01   F     No   Sun  Dinner     2
1         10.34  1.66   M     No   Sun  Dinner     3
2         21.01  3.50   M     No   Sun  Dinner     3
3         23.68  3.31   M     No   Sun  Dinner     2
4         24.59  3.61   F     No   Sun  Dinner     4
..          ...   ...  ..    ...   ...     ...   ...
239       29.03  5.92   M     No   Sat  Dinner     3
240       27.18  2.00   F    Yes   Sat  Dinner     2
241       22.67  2.00   M    Yes   Sat  Dinner     2
242       17.82  1.75   M     No   Sat  Dinner     2
243       18.78  3.00   F     No  Thur  Dinner     2

[244 rows x 7 columns]

In [109]:
simple_df = pd.DataFrame([1,2,2,2],[1,2,2,2]) 
display(
    simple_df.duplicated() # true if duplicated in that particular array / list
)

1    False
2    False
2     True
2     True
dtype: bool